#document settings

title: Financial Management Line of Business (FMLoB)
desc: "Collaboration Space"
url: /fedfmdataelements.github.io
repo_name: fedfmdataelements.github.io
branch: master
encoding: utf-8

#global settings, no need to change these
root_url: //fedfmdataelements.github.io
org_name: fedfmdataelements

# default build settings for running locally, no need to edit
highlighter: rouge
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "LICENSE"]
markdown: kramdown
# markdown: redcarpet
# redcarpet:
#   extensions: []
relative_permalinks: false

gems:
 - jekyll-redirect-from

whitelist:
 - jekyll-redirect-from

navigation:
 - title: Home
   url: /index.html
 - title: Business Exchange
   url: /data-elements
 - title: Get Involved
   url: /get-involved

sass:
  sass_dir:          assets/_scss
  #style:            :compressed
